import assert from 'node:assert/strict';
import {analyze,sampleSites,validateRows,defaults,budgetSelection,isCsvFile} from '../lib/ecology.ts';
import {assessAnomalies,calculateWeightSensitivity,clusterEcologicalProfiles,getDataReadiness,latestSiteProfiles,uniqueSiteArea} from '../lib/analytics.ts';
assert.equal(isCsvFile({name:'data.csv',type:'text/csv'}),true);
assert.equal(isCsvFile({name:'data.xlsx',type:'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet'}),false);
assert.deepEqual(validateRows([{...sampleSites[0], area_km2: 2.5, area_ha: undefined}]).map(s => s.area_ha), [250]);
assert.equal(validateRows([{...sampleSites[0], site_id:'tn-site-1', observation_id:'obs-1'}])[0].site_id,'tn-site-1');
assert.equal(validateRows([{...sampleSites[0], data_status:undefined, provenance_type:undefined}])[0].provenance_type,'unknown');
assert.equal(validateRows(sampleSites).length,12);
assert.throws(()=>validateRows([{...sampleSites[0],vegetation_pct:''}]),/required/);
assert.throws(()=>validateRows([sampleSites[0],sampleSites[0]]),/duplicate/);
assert.throws(()=>validateRows([{...sampleSites[0],latitude:91}]),/latitude/);
assert.throws(()=>validateRows([{...sampleSites[0],observed_at:'2026-02-31'}]),/date/);
assert.equal(analyze({...sampleSites[0],vegetation_pct:100,soil_health:100,water_stress:0,biodiversity:100,erosion_risk:0}).score,0);
assert.equal(analyze({...sampleSites[0],vegetation_pct:0,soil_health:0,water_stress:100,biodiversity:0,erosion_risk:100}).score,100);
assert.equal(analyze(sampleSites[0],{vegetation:100,soil:0,water:0,biodiversity:0,erosion:0}).score,78);
assert.throws(()=>analyze(sampleSites[0],{vegetation:0,soil:0,water:0,biodiversity:0,erosion:0}),/positive/);
const ranked=sampleSites.map(s=>analyze(s));const scenario=budgetSelection(ranked,2000000);assert.ok(scenario.spent<=2000000);assert.equal(budgetSelection(ranked,0).selected.length,0);
const clusters=clusterEcologicalProfiles(sampleSites,17);assert.equal(clusters.status,'ready');assert.equal(Object.keys(clusters.membership).length,sampleSites.length);assert.ok(clusters.silhouette>=-1&&clusters.silhouette<=1);assert.deepEqual(clusterEcologicalProfiles(sampleSites,17),clusters);
assert.equal(clusterEcologicalProfiles(sampleSites.slice(0,2)).status,'unavailable');
assert.match(clusterEcologicalProfiles([...sampleSites.slice(0,2),{...sampleSites[2],vegetation_pct:NaN}]).reason,/missing values/);
assert.equal(clusterEcologicalProfiles(sampleSites.map(s=>({...s,vegetation_pct:50,soil_health:50,water_stress:50,biodiversity:50,erosion_risk:50}))).status,'unavailable');
const outlier=[...sampleSites.slice(0,4),{...sampleSites[4],vegetation_pct:0,soil_health:0,water_stress:100,biodiversity:0,erosion_risk:100}];assert.ok(assessAnomalies(outlier).some(item=>item.recordId===sampleSites[4].id&&item.unusual));
const sensitivityA=calculateWeightSensitivity(ranked,defaults,{samples:32,seed:9});const sensitivityB=calculateWeightSensitivity(ranked,defaults,{samples:32,seed:9});assert.deepEqual(sensitivityA,sensitivityB);assert.ok(sensitivityA.every(item=>item.minimumRank>=1&&item.maximumRank<=ranked.length&&item.topFrequency>=0&&item.topFrequency<=100));
assert.throws(()=>calculateWeightSensitivity(ranked,{vegetation:0,soil:0,water:0,biodiversity:0,erosion:0}),/positive/);
assert.equal(getDataReadiness(sampleSites).supervisedReady,false);
const repeated=[{...sampleSites[0],site_id:'stable-1',provenance_type:'observed',data_status:'observed',reviewer_status:'accepted',reviewed_priority_score:60},{...sampleSites[1],site_id:'stable-1',provenance_type:'observed',data_status:'observed',reviewer_status:'accepted',reviewed_priority_score:65}];assert.equal(getDataReadiness(repeated).independentLabeledSites,1);assert.equal(getDataReadiness(repeated).supervisedReady,false);assert.equal(uniqueSiteArea(repeated),sampleSites[0].area_ha);
const followup={...sampleSites[0],id:'TN-001-followup',site_id:sampleSites[0].id,observation_id:'TN-001-followup',observed_at:'2026-12-01',vegetation_pct:sampleSites[0].vegetation_pct+1};const followupProfiles=latestSiteProfiles([...sampleSites,followup]);assert.equal(followupProfiles.length,sampleSites.length);assert.equal(followupProfiles.find(site=>(site.site_id??site.id)===sampleSites[0].id)?.observed_at,'2026-12-01');const followupClusters=clusterEcologicalProfiles([...sampleSites,followup]);assert.equal(followupClusters.trainingSampleCount,sampleSites.length);assert.equal(followupClusters.membership[followup.id],followupClusters.membership[sampleSites[0].id]);assert.equal(Object.values(followupClusters.clusters).reduce((sum,cluster)=>sum+cluster.size,0),sampleSites.length);
const changed=analyze({...sampleSites[0],vegetation_pct:90},defaults);assert.ok(changed.score<ranked[0].score);
const {GET}=await import('../app/api/weather/route.ts');assert.equal((await GET(new Request('http://localhost/api/weather?lat=999&lon=78'))).status,400);
console.log('PASS: validation, provenance, repeated-site identity, K-means reproducibility and missing-value gate, anomaly review, supervised readiness, unique-site area, weight sensitivity, baseline scoring, and budget');
